version: '3'
services: 
  webserver:
    image: nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./:/usr/share/nginx/html